### ISSUE TITLE
Mac Catalyst issue with Cocoapods

### ISSUE THREAD

**Issue by willm132** [jmcnamara/libxlsxwriter#337] opened 2021-06-09 20:19 UTC
When compiling for Mac Catalyst I am getting this error:

Undefined symbols for architecture x86_64:
"_format_set_bold",
"_format_set_border",
"_format_set_border_color"
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jmcnamara** [comment] 2021-06-09 22:14
The is just a standard link error. Make such that `-lxlsxwriter` is on you link command line. She the standard variations here: https://libxlsxwriter.github.io/getting_started.html#gsg_using

**Comment by willm132** [comment] 2021-06-09 22:45
@jmcnamara I am using CocoaPods with Xcode

**Comment by jmcnamara** [comment] 2021-06-10 06:43
> I am using CocoaPods with Xcode

In that case I can't help you much since I don't use CocoaPods myself. Try the following sample code and see if it works: https://github.com/FrankenApps/LibXlsxWriterSwiftSample

**Comment by willm132** [comment] 2021-06-10 13:34
I use Intel iMac and M1 MacBook Pro

**Comment by jmcnamara** [comment] 2021-06-10 13:43
Do you see the same issue on both systems?

**Comment by jmcnamara** [comment] 2021-06-10 14:20
Ok. Can you try the sample app linked above and see if it works.

**Comment by willm132** [comment] 2021-06-10 14:24
Yes, the sample did compile and work on Mac Catalyst. What do I need to do to get my project working?

**Comment by jmcnamara** [comment] 2021-06-10 14:36
I'd suggest using the sample application and add functionality until it is similar to the app you are trying to compile and use that to figure out why your project isn't working.

Either way I don't think this is a general libxlsxwriter issue, or something that I can help you with, so I am going to close this.

**Comment by willm132** [comment] 2021-06-10 19:24
When running via Sample it complies and runs fine, but if I try to build to export via AdHoc I am getting this error:

Umbrella header 'xlsxwriter/libxlsxwriter-umbrella.h' not found

**Comment by jmcnamara** [comment] 2021-06-10 20:25
@FrankenApps could you help with this issue.

**Comment by FrankenApps** [comment] 2021-06-11 03:28
I don't have an Apple Developer Account, so there isn't really a way I could reproduce this. I will still try and have a look...

**Comment by willm132** [comment] 2021-06-11 12:05
Like I said it runs fine on the machine but will not archive

**Comment by willm132** [comment] 2021-06-14 15:59
Any updated on this?

**Comment by jmcnamara** [comment] 2021-06-14 16:50
Hi Will, you may have better luck on a Catalyst or Cocoapod forum, or StackOverflow. There probably aren't too many Catalyst/Cocoapod users on here. 

If you find a solution let us know.

**Comment by FrankenApps** [comment] 2021-06-14 18:27
@willm132 Have you checked [this](https://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found)?

**Comment by willm132** [comment] 2021-06-14 18:28
@FrankenApps yes I actually did try that but no luck still

**Comment by FrankenApps** [comment] 2021-06-14 18:37
Does it work when generating a signed .ipa? As stated above there is no real way to reproduce this for me...

**Comment by willm132** [comment] 2021-06-14 18:39
If I run it from Xcode it installs on the device and works fine, when I go to Project > Archive, this is when it gives me the error

**Comment by FrankenApps** [comment] 2021-06-14 19:20
Aha, now I understood. But this only happens when archiving for mac. You can archive it just fine for iOS.

**Comment by willm132** [comment] 2021-06-14 19:21
Yes, my project supports Mac Catalyst.

**Comment by willm132** [comment] 2021-06-14 19:27
BuildProductsPath/Release-maccatalyst/libxlsxwriter/xlsxwriter.framework/Modules/module.modulemap:2:19: Umbrella header 'xlsxwriter/libxlsxwriter-umbrella.h' not found

Could not build Objective-C module 'xlsxwriter'

This is the error I get when trying to archive.

**Comment by FrankenApps** [comment] 2021-06-14 19:44
Well, I do know what the Issue is, but I don't know how to fix it.

There should be an `alias` for the `Headers` in `BuildProductsPath/Release-maccatalyst/libxlsxwriter/xlsxwriter.framework`, but it is not there.

Current:
![Bildschirmfoto 2021-06-14 um 21 42 45](https://user-images.githubusercontent.com/17967303/121950171-9590a480-cd59-11eb-9707-ad93bdf30bec.png)

How it should be (Sourceful does this right):
![Bildschirmfoto 2021-06-14 um 21 43 07](https://user-images.githubusercontent.com/17967303/121950231-a5a88400-cd59-11eb-9b15-8d19ae46877c.png)

**Comment by willm132** [comment] 2021-06-14 19:45
Is this something I can manually add on my end to resolve this?

**Comment by FrankenApps** [comment] 2021-06-14 19:57
I don't know. Might have something to do with `Header Search Paths`, but I don't know how to fix this. It should be possible to add this alias with a build script, because we know, that it should target `Pods/libxlsxwriter/include`, but I am definitely not an expert and have no idea how to do this. Also I don't know, why it works for debug builds, because as far as I can tell the settings are exactly the same...

**Comment by willm132** [comment] 2021-06-14 19:59
My header search path contains "${PODS_CONFIGURATION_BUILD_DIR}/libxlsxwriter/xlsxwriter.framework/Headers".

Is this an issue with Libxlsxwriter or my project?

**Comment by jmcnamara** [comment] 2021-06-14 20:04
This issue looks similar to this one: https://github.com/CocoaPods/CocoaPods/issues/10354

Maybe try update to the latest, beta, cocoapod framework to see if it fixes the issue, as suggested there.

**Comment by willm132** [comment] 2021-06-14 20:07
So how would I go about updating to Cocoapods 1.10.2 beta?

**Comment by jmcnamara** [comment] 2021-06-14 20:14
You can try this: 

    gem install cocoapods --pre

As suggested here: https://guides.cocoapods.org/using/getting-started.html

**Comment by willm132** [comment] 2021-06-14 20:16
That just installed 1.10.1

**Comment by willm132** [comment] 2021-06-14 20:17
Would this have something to do with it? after running pod update

[!] The `Graf Brothers [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Graf Brothers/Pods-Graf Brothers.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Graf Brothers [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Graf Brothers/Pods-Graf Brothers.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Graf BrothersUITests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Graf Brothers-Graf BrothersUITests/Pods-Graf Brothers-Graf BrothersUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Graf BrothersUITests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Graf Brothers-Graf BrothersUITests/Pods-Graf Brothers-Graf BrothersUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by willm132** [comment] 2021-06-14 20:26
@FrankenApps 

gem install cocoapods --pre

This installed 1.10.1 which is resulting in the same error

**Comment by jmcnamara** [comment] 2021-06-14 20:29
In that case you will probably need to install the version in the GitHub repo. I haven't done that before but I presume there is some gem command.

**Comment by FrankenApps** [comment] 2021-06-14 20:30
I was able to sucessfully build my demo project for Catalyst with [that](https://github.com/grpc/grpc/issues/20500#issuecomment-604889919) method on 1.10.1

**Comment by willm132** [comment] 2021-06-14 20:33
So just throw that in a script file and run it while I archive my project?

**Comment by FrankenApps** [comment] 2021-06-14 20:36
Yes, and adjust the paths to your local setup.

**Comment by jmcnamara** [comment] 2021-06-15 10:37
There was an update on the [Cocoapods #10224](https://github.com/CocoaPods/CocoaPods/pull/10224) about how to [use  Unreleased Cocoapod Features](https://guides.cocoapods.org/using/unreleased-features).

Here is a summary of how to get a version of pod with the fix for issue 10224 built in:

```bash
# This took a couple of goes:
$ bundle update --bundler


$ cd /tmp
$ git clone git@github.com:CocoaPods/CocoaPods.git
$ cd CocoaPods/
$ git checkout 1-10-stable
$ bundle install
$ echo $(pwd)"/bin/pod"

# So now you should have a patched version of pod. For me this was:
$ echo $(pwd)"/bin/pod"
/tmp/CocoaPods/bin/pod

# Then use this version of pod to install libxlsxwriter:
/tmp/CocoaPods/bin/pod install
```

Could one of you try that to see if it works.

**Comment by willm132** [comment] 2021-06-15 11:55
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by jmcnamara** [comment] 2021-06-15 12:11
@FrankenApps 

Try the https version instead:

```
git clone https://github.com/CocoaPods/CocoaPods.git
```

**Comment by willm132** [comment] 2021-06-15 12:13
Yes that is what I did to get it working. 

I installed the new CocoaPods, created an alias in terminal for it, ran the new pod update, and that worked! Thank you so much for all the help

**Comment by willm132** [comment] 2021-06-15 12:15
However, I am not getting this issue. Found an unexpected Mach-O header code: 0x72613c21

**Comment by jmcnamara** [comment] 2021-06-15 12:32
@willm132 that seems to be a somewhat common issue (based on google hits). Try some of the suggested solutions (like [this](https://kobkrit.com/how-to-fix-found-an-unexpected-mach-o-header-code-0x72613c21-on-submitting-to-app-store-7d5b8ec180c)) and let us know how you get on.

**Comment by jmcnamara** [comment] 2021-06-17 22:34
I'm going to close this again since the original reported issue should be fixed.

**Closed by jmcnamara** 2021-06-17 22:34 UTC
