### ISSUE TITLE
metadata.h and .c missing from Cocoapod?

### ISSUE THREAD

**Issue by jkichline** [jmcnamara/libxlsxwriter#346] opened 2021-07-22 20:03 UTC
<img width="2240" alt="Screen Shot 2021-07-22 at 4 04 04 PM" src="https://user-images.githubusercontent.com/377033/126702587-a6d77b7b-843f-4955-9a21-31e0d6211981.png">
I'm seeing an issue when setting up my project that uses libxlsxwriter where after a pod update and compile, the project is not compiling because metadata.h file not found. Is this an error in the CocoaPods as I see the code in the GitHub repository.

**Comment by jmcnamara** [comment] 2021-07-22 20:31
I think this may be a known Cocoapod issue. See #337 and the workaround discussed there.

**Comment by jkichline** [comment] 2021-07-22 21:30
The files are not being downloaded nor are they present with the v1.1.1 of the framework. If I change my Podfile to download the previous version such as v1.0.9, the project compiles properly. It appears to be an issue that has started in v1.1.1. I am working to get the project working on an M1 but have not had issues with libxlsxwriter previously. There appears to be N issue with the pod configuration?

**Comment by jmcnamara** [comment] 2021-07-22 22:01
> If I change my Podfile to download the previous version such as v1.0.9, the project compiles properly. It appears to be an issue that has started in v1.1.1.

Does the issue happen with v1.1.0?

Also, can you try the workaround for the know issue discussed in #337. Namely, try this version of pod:

```bash
# This took a couple of goes:
$ bundle update --bundler


$ cd /tmp
$ git clone git@github.com:CocoaPods/CocoaPods.git
$ cd CocoaPods/
$ git checkout 1-10-stable
$ bundle install
$ echo $(pwd)"/bin/pod"

# So now you should have a patched version of pod. For me this was:
$ echo $(pwd)"/bin/pod"
/tmp/CocoaPods/bin/pod

# Then use this version of pod to install libxlsxwriter:
/tmp/CocoaPods/bin/pod install
```

**Comment by jmcnamara** [comment] 2021-07-23 08:14
@FrankenApps could you have a look at this issue and see if you can reproduce it.

**Comment by FrankenApps** [comment] 2021-07-25 08:25
I tried to reproduce this, but failed to do so. 
I've upgraded my example project to `1.1.1` and it still build without issues. 

Both [metadata.c](https://github.com/FrankenApps/LibXlsxWriterSwiftSample/tree/master/Pods/libxlsxwriter/src) and [metadata.h](https://github.com/FrankenApps/LibXlsxWriterSwiftSample/tree/master/Pods/libxlsxwriter/include/xlsxwriter) are still present.

@jkichline Are you building the project for Catalyst or for iOS?

**Comment by jmcnamara** [comment] 2021-07-25 09:23
Thanks @FrankenApps 

@jkichline can you try @FrankenApps sample app: https://github.com/FrankenApps/LibXlsxWriterSwiftSample

**Comment by jmcnamara** [comment] 2021-07-26 18:46
@jkichline any update on this?

**Comment by jkichline** [comment] 2021-07-26 18:49
I’m reaching out to the cocoapod catalyst support project https://github.com/fermoya/cocoapods-catalyst-support/ <https://github.com/fermoya/cocoapods-catalyst-support/>

One thing you had mentioned is the version of Cocoapods being used and to install Catalyst support it seems to update Cocoapods and I wonder if that’s causing the incompatibility. Of course the same exact Podfile works on Intel but on M1, event if reverting to an earlier version of the xlsxwriter, a different Cocoapod will trigger and be missing a file so I think it’s an issue with the catalyst support project on the M1 perhaps?  I’ll let you know when they get back.

**Comment by jmcnamara** [comment] 2021-07-26 22:26
Interesting. What is the version number string in the xlsxwriter.h file in your project?

**Comment by jkichline** [comment] 2021-07-27 13:07
The version that I have installed right now that does work is 1.0.9.  If I pod update to the latest version, that is the one that skips the metadata files and that version is 1.1.1

**Comment by jmcnamara** [comment] 2021-08-08 20:27
I'm going to close this here since I don't think it is a libxlsxwriter pod issue. BTW, there is an new libxlsxwriter pod (1.1.2) out as of today. You can try that to see if it makes any difference.

**Closed by jmcnamara** 2021-08-08 20:27 UTC
Labels: under investigation
