### ISSUE TITLE
Problem using libxlsxwriter and ZipArchive together

### ISSUE THREAD

**Issue by sanhue0302** [jmcnamara/libxlsxwriter#55] opened 2016-06-29 04:58 UTC
while i use pod libxlsxwriter and ZipArchive together
build would failed with  "Use of undeclared identifier 'MAXU32'"
i think that because pod will misunderstand include ioapi.h at Ziparchive rather than libxlsxwriter 
any idea to use these two together?

**Comment by jmcnamara** [comment] 2016-06-29 07:30
Hi Sanhue,

There isn't very much information to go on here.

Some questions:

1. What is ZipArchive? I presume this: https://cocoapods.org/pods/ZipArchive
2. What are the steps to reproduce this? Please give a complete example.

I took a quick look at the ZipArchive source and the version of ioapi.h isn't wrapped in a `#ifndef _ZLIBIOAPI64_H` sentinel. Or perhaps it isn't a recent version from the [zlib master branch](https://github.com/madler/zlib/tree/master/contrib/minizip). You could try replacing the minizip parts in ZipArchive with the ones from zlib master or libxlsxwriter.

John

**Comment by sanhue0302** [comment] 2016-06-29 07:37
a simple way to reproduce this issue is:

- create a new project
- add a podfile with

> 

      pod 'ZipArchive'
      pod 'libxlsxwriter'
- pod update
- build the workspace

**Comment by sanhue0302** [comment] 2016-06-29 07:40
yes, i think ZipArchive and libxlsxwriter use different version of minzip 

any idea to solve the problem?

**Comment by jmcnamara** [comment] 2016-06-29 07:43
> yes, i think ZipArchive and libxlsxwriter use different version of min zip . any idea to solve the problem?

Just the idea that I suggested above. To replace the minizip version in ZipArchive with the one from zlib master (or the 1.28 tarball) or the one from libxlsxwriter.

**Comment by jmcnamara** [comment] 2016-06-29 08:45
Can you also post a full error log.

**Comment by jmcnamara** [comment] 2016-06-29 08:48
P.S. An error log when using SSArchiveZip.

**Comment by sanhue0302** [comment] 2016-06-29 08:58
/Users/sanhue/Desktop/test/Pods/libxlsxwriter/third_party/minizip/ioapi.c:62:29: error: use of undeclared identifier 'MAXU32'
        if ((tell_uLong) == MAXU32)

my test sample:
[test.zip](https://github.com/jmcnamara/libxlsxwriter/files/338879/test.zip)

**Comment by jmcnamara** [comment] 2016-07-02 14:53
@lrossi Any chance you could take a look at this issue if you get some time. Basically there is some sort of incompatibility between libxlsxwriter and SSArchiveZip with installed from pods since they both include a complete copy of minizip from zlib.

I don't know enough about either Xcode or Cocoapods to help the OP resolve their issue.

**Comment by jmcnamara** [comment] 2016-12-20 09:39
Closing. Can't fix.

**Closed by jmcnamara** 2016-12-20 09:39 UTC
Labels: bug
