### ISSUE TITLE
Incorrect image aspect ratio when image width exceeds column width

### ISSUE THREAD

**Issue by evanmiller** [jmcnamara/libxlsxwriter#303] opened 2020-08-19 16:40 UTC
I'm not sure about the exact circumstances that produce this, but here is the code:

```C
lxw_image_options options = {
    .x_offset = 1, .y_offset = 2,
    .x_scale = 0.5, .y_scale = 0.5,
    .object_position = LXW_OBJECT_MOVE_DONT_SIZE
};
worksheet_insert_image_buffer_opt(cws, excel_row, excel_col, data.bytes, data.length, &options);
```

The inserted PNG image is 140 x 140 @ 300dpi. However, the resulting XLSX scales the image down by different amounts along each axis:

<img width="649" alt="xlsx" src="https://user-images.githubusercontent.com/134711/90664167-9da2b500-e218-11ea-9d8b-cc0867236b18.png">

I notice that libxlsxwriter will correctly preserve aspect ratio if I decrease the image size below the column width, or increase the column width to exceed the image width.

I am *not* using `constant_memory` = true so I don't think this is a duplicate of #284.

**Comment by jmcnamara** [comment] 2020-08-19 18:33
Can you attach the image so I can reproduce this.

**Comment by evanmiller** [comment] 2020-08-19 18:37
![image1](https://user-images.githubusercontent.com/134711/90676084-67b9fc80-e229-11ea-9de0-61df6e774048.png)

**Comment by jmcnamara** [comment] 2020-08-19 18:37
Also, I notice that the row height with the image is changed. Is that change implicit or explicit? See this section of the docs on [Object scaling due to automatic row height adjustment](http://libxlsxwriter.github.io/working_with_object_positioning.html) for an explanation.

**Comment by evanmiller** [comment] 2020-08-19 18:39
Row height is set programmatically:

```C
worksheet_set_row(cws, excel_row, LXW_DEF_ROW_HEIGHT * 5, NULL);
```

There is text in the row but it is the standard font and does not wrap.

**Comment by jmcnamara** [comment] 2020-08-19 19:22
Attaching file created in Excel for reference: [gh303_excel.xlsx](https://github.com/jmcnamara/libxlsxwriter/files/5098805/gh303_excel.xlsx)

**Comment by jmcnamara** [comment] 2020-08-19 19:44
I've seen this issue before. It seems to affect Excel on macOS. For example the file above was created in Excel 2007 on a Windows VM. In Excel 2011 and Excel 2016/365 for macOS it shows the scaling issue you report:

![Screenshot 2020-08-19 at 20 43 06](https://user-images.githubusercontent.com/94267/90682261-9bfae080-e25c-11ea-9b1c-bad293fc6790.png)

However with Excel 2015/365 on another Windows machine it looks fine:

(I'll add the image shortly)

**Comment by jmcnamara** [comment] 2020-08-19 20:02
I don't know what causes this. Libxlsxwriter duplicates the Excel 2007 behaviour and there are currently 84 test cases to ensure that it matches Excel for a range of different images in different positions and scales.

Maybe you can verify the behaviour yourself by creating an Excel file with an image on a Windows machine and transferring it to Excel on the mac.

I also found this explanation from MS (which doesn't explain why it is only the vertical scaling is different): https://answers.microsoft.com/en-us/msoffice/forum/all/size-of-images-changes-mac-windows/cc9009dc-27d4-4620-8649-514881bb9e3a

**Comment by evanmiller** [comment] 2020-08-19 20:28
There's some strange trigger with the column width - in certain ranges, shrinking the column produces the correct aspect ratio. I wonder if there's some kind of "snap to cell width" logic when the right image border is close to a cell border.

**Comment by jmcnamara** [comment] 2020-08-19 21:59
@evanmiller Ok. If you create a test case with the sample above I will look into it.

**Comment by evanmiller** [comment] 2020-08-20 01:05
If your test file opens on Windows OK, then I'm willing to chalk it up to a Microsoft bug. It's a frustrating one, though!

**Comment by jmcnamara** [comment] 2020-08-20 22:10
> It's a frustrating one, though!

It is. Especially since any differences in image scaling are immediately visible. It is doing the same thing for other worksheet objects such as charts and buttons but those changes aren't obvious. It is also frustrating since I put a lot of reverse-engineering work into matching Excel's behaviour on Windows.

Since there is nothing that I can do here I'm going to close this.

**Closed by jmcnamara** 2020-08-20 22:10 UTC

**Comment by bdkjones** [comment] 2024-04-06 23:33
Just chiming in to say this is still an issue in 2024. I have exactly the same problem: if I insert an image such that its right edge is "too close" to a column, the image's aspect ratio is mutilated and it "snaps" to the column boundary.

The only solution I've found is to make the column much wider than necessary.

The same behavior manifests when the *.xlsx file is opened in Apple Numbers. Clicking "original size" in the image inspector within Numbers restores the correct aspect ratio.

**Comment by bdkjones** [comment] 2024-04-07 04:45
After hours of fighting, I've settled on a (very clunky) workaround. 

The spreadsheet I'm building has a column of images, each of which SHOULD be a 16:9 (1.77777) aspect ratio. But if I size the images such that their right edge is closer than roughly 20 pixels to the right border of the cell, the aspect ratio is distorted—*but distorted in a predictable fashion*. 

The images' aspect ratio ends up at 2.002. So in my `lxw_image_options`, I just supply a `yScale` factor to correct this nonsense. The image is still "snapped" to the cell width, but I can now ensure that it retains the correct aspect ratio when that happens.

I haven't tested the resulting spreadsheets on Excel for Windows. Microsoft never really got into high-resolution screens like Apple did, so I'm not shocked there's a bunch of weirdness or that they rely on 72 and 96 DPI.

**Comment by slw287r** [comment] 2024-04-07 07:58
I've similar workaround when the cell height is more than expected if I specify monospace font such as "Courier New" for multiple-line string set to align vertically top by the format `LXW_ALIGN_VERTICAL_TOP`.

The trick is to make the row height slightly smaller:

```
worksheet_set_row(worksheet, row_number, LXW_DEF_ROW_HEIGHT / 1.001, NULL);
```

**Comment by jmcnamara** [comment] 2024-04-07 15:21
> Just chiming in to say this is still an issue in 2024. I have exactly the same problem: if I insert an image such that its right edge is "too close" to a column, the image's aspect ratio is mutilated and it "snaps" to the column boundary.

Folks, I understand the frustration here but I need to reiterate that this isn't a libxlsxwriter issue, it is a Mac/Windows Excel issue. This is easily reproducible outside of libxlsxwriter and the link above https://github.com/jmcnamara/libxlsxwriter/issues/303#issuecomment-676632897 shows that general Excel users also encounter this issue.

For cases where the image is in a single cell it should be resolved by Excel's newer embedded image option that I will implement as part of #417.

**Comment by bdkjones** [comment] 2024-04-07 17:08
I should have been more clear: it's still an issue with Excel. I was simply posting my workaround in case it helps others who encounter the problem.

**Comment by bdkjones** [comment] 2024-04-07 19:20
@jmcnamara This thread is a weird place for the discussion, but the Rust version of libxlxswriter has just a fraction of the interest that the C and Python versions have (although the Rust repo is likely newer, so there's an age bias).

I don't have any experience with Rust, but I understand it can be compiled to a static C library. That would make it much more useable for app developers and would also obviate the need to maintain the C version of libxlsxwriter, which frees up your time.

Perhaps that's a better way forward than maintaining the library in triplicate?
