### ISSUE TITLE
ZLIB_ROOT ingored warning

### ISSUE THREAD

**Issue by John-Colvin** [jmcnamara/libxlsxwriter#243] opened 2019-08-30 07:43 UTC
```
CMake Warning (dev) at CMakeLists.txt:163 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    C:\Users\John Colvin\AppData\Local\dub\packages\xlsxd-3.1.8\xlsxd\\install_dir\zlib

  For compatibility, CMake is ignoring the variable.
```

I'm guessing you should set the policy in `CmakeLists.txt`, but I don't really know cmake

**Comment by jmcnamara** [comment] 2019-08-30 09:21
I think this may be a duplicate of #242 Can you check, and if it is, add your comments/analysis over there and I'll try to reply in one place.

**Comment by John-Colvin** [comment] 2019-08-30 12:49
I don't think so, but it's possible if this was fixed it would fix #242 

Someone with more knowledge about cmake would probably know better.

**Comment by evanmiller** [comment] 2019-08-31 15:18
@John-Colvin What version of CMake are you using?

**Comment by Alexhuszagh** [comment] 2019-09-03 15:05
@evanmiller This is actually an issue with new CMake versions. Confirmed as of Cmake `3.14.5`, the error makes it clear this has been an issue since CMake `3.12`.

**Comment by Alexhuszagh** [comment] 2019-09-03 15:28
@John-Colvin Let me know if the following PR works for you:
https://github.com/jmcnamara/libxlsxwriter/pull/246

**Comment by jmcnamara** [comment] 2019-09-05 08:15
@John-Colvin  Can you test the proposed fix.

**Comment by Alexhuszagh** [comment] 2019-09-08 14:55
@jmcnamara I'm very certain this should patch the issue, and at the very least, it will patch a similar issue due to CMake introducing a backward compatibility issue, so it might be preferable to commit any changes if there's no reply.

**Comment by jmcnamara** [comment] 2019-09-08 18:48
@Alexhuszagh Agreed. Fix is merged.

@John-Colvin I'm closing this issue. You can test against the current master to see if your issues is fixed. If it isn't then open a new issue, with details on how to reproduce, or post a follow-up here.

**Closed by jmcnamara** 2019-09-08 18:48 UTC
Labels: bug, cmake
