### ISSUE TITLE
Fails to install in ArchLinux

### ISSUE THREAD

**Issue by mantielero** [jmcnamara/libxlsxwriter#329] opened 2021-05-10 19:56 UTC
I am trying to install in ArchLinux, but I am getting:
```
$ nimble install
   Warning: Package 'nimlibxlsxwriter' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nimlibxlsxwriter', but file 'doc_custom_properties.nim' is in a directory named 'tests' instead. This will be an error in the future.
      Hint: If 'tests' contains source files for building 'nimlibxlsxwriter', rename it to 'nimlibxlsxwriter'. Otherwise, prevent its installation by adding `skipDirs = @["tests"]` to the .nimble file.
Setting up Git repo: https://github.com/jmcnamara/libxlsxwriter
Pulling repository
Command failed: 1
git pull --depth=1 origin master
fatal: no se puedo encontrar ref remota master

stack trace: (most recent call last)
/tmp/nimblecache-1023837959/nimscriptapi_3203592219.nim(199, 29)
/tmp/nimlibxlsxwriter/nimlibxlsxwriter.nimble(24, 14) installBefore
/tmp/nimlibxlsxwriter/nimlibxlsxwriter.nimble(21, 10) setupTask
/home/jose/.choosenim/toolchains/nim-#devel/lib/system/nimscript.nim(273, 7) exec
/home/jose/.choosenim/toolchains/nim-#devel/lib/system/nimscript.nim(273, 7) Error: unhandled exception: FAILED: nimgen nimlibxlsxwriter.cfg [OSError]
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Exception raised during nimble script execution
```

I am using nim v1.5.1 on amd64.

**Comment by jmcnamara** [comment] 2021-05-10 20:17
This is the issue tracker for libxlsxwriter not nimlibxlsxwriter (which I don't have anything to do with). 

Nevertheless the issue is that the main libxlsxwriter branch is called "main" now and not "master". Try changing your local build file and/or report to the maintainer of nimlibxlsxwriter.

Closing.

**Closed by jmcnamara** 2021-05-10 20:17 UTC
