### ISSUE TITLE
Issues building libxlswriter on Gentoo Linux with system minizip

### ISSUE THREAD

**Issue by petricf** [jmcnamara/libxlsxwriter#116] opened 2017-08-10 10:47 UTC
On Gentoo Linux minizip is usually installed system wide. This conflicts with the packaged minizip.

The following patches remove the dependency in CMakeLists.txt and adjust the include in packager.h
They are based on the 0.7.2 release.

My suggestion is to add an option for cmake to use the system minizip instead of the built in one.
Sorry - i don't know much on cmake, so maybe an other one will step in.

[patches.zip](https://github.com/jmcnamara/libxlsxwriter/files/1214593/patches.zip)

**Comment by jmcnamara** [comment] 2017-08-10 11:42
Hi @petricf,

Thanks for the report.

1. Could you add some instruction on how to replicate the issues on Gentoo?
2. Does the issue happen if you use the Makefile based build system?

John

**Comment by petricf** [comment] 2017-08-10 15:11
Hello,

imho this is a problem in which the sequence of include directories are scanned for header 
files - system vs. packaged. 

1. How ro replicate.

Gentoo uses a *.ebuild file contining instructions on how to build integrate a package into 
the system. Mine reads this way w/o patches):
----------------- cut ----------------------
EAPI=5 
*inherit* cmake-utils 
DESCRIPTION=*"An C implementation of an excel writer"* 
HOMEPAGE=*"https://github.com/jmcnamara/libxlsxwriter"* 
SRC_URI=*"https://github.com/jmcnamara/${PN}/archive/RELEASE_${PV}.tar.gz -> 
${P}.tar.gz"* 
LICENSE=*"BSD-2"* # FreeBSD 
SLOT=*"0"* 
KEYWORDS=*"amd64 x86"* 
RDEPEND=*"sys-libs/zlib[minizip]"* 
DEPEND=*"${RDEPEND}"* 
S=*"${WORKDIR}/${PN}-RELEASE_${PV}"* 
----------------- cut ----------------------

All the build and install rules a built in. This is referred by the second line "inherit cmake-
utils". I do not know what sequence of commands are executed here.

Simply place the file above as "libxlsxwriter-0.7.2.ebuild" into the (local) portage tree of 
gentoo. The output can be viewed in the attached file "build.log" (sorry, it's german and 
colored/escape codes).


2. Use pre-packaged Makefile.

The output rather is the same
----------------- cut ----------------------
*petric@main ~/libxlsxwriter-RELEASE_0.7.2 $* LANG=en_US.UTF-8 make 
*ioapi.c:29:0*: 
*ioapi.h:135:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:136:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:137:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:138:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:139:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:141:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:142:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:148:5:* *error: *unknown type name ‘*open_file_func*’ 
*    ^* 
*ioapi.h:149:5:* *error: *unknown type name ‘*read_file_func*’ 
*    ^* 
*ioapi.h:150:5:* *error: *unknown type name ‘*write_file_func*’ 
*    ^* 
*ioapi.h:151:5:* *error: *unknown type name ‘*tell_file_func*’ 
*    ^* 
*ioapi.h:152:5:* *error: *unknown type name ‘*seek_file_func*’ 
*    ^* 
*ioapi.h:153:5:* *error: *unknown type name ‘*close_file_func*’ 
*    ^* 
*ioapi.h:154:5:* *error: *unknown type name ‘*testerror_file_func*’ 
*    ^* 
*ioapi.h:158:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:159:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:160:51:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                                                  ^* 
*ioapi.h:164:5:* *error: *unknown type name ‘*open64_file_func*’ 
*    ^* 
*ioapi.h:165:5:* *error: *unknown type name ‘*read_file_func*’ 
*    ^* 
*ioapi.h:166:5:* *error: *unknown type name ‘*write_file_func*’ 
*    ^* 
*ioapi.h:167:5:* *error: *unknown type name ‘*tell64_file_func*’ 
*    ^* 
*ioapi.h:168:5:* *error: *unknown type name ‘*seek64_file_func*’ 
*    ^* 
*ioapi.h:169:5:* *error: *unknown type name ‘*close_file_func*’ 
*    ^* 
*ioapi.h:170:5:* *error: *unknown type name ‘*testerror_file_func*’ 
*    ^* 
*ioapi.h:174:28:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                           ^* 
*ioapi.h:175:26:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                         ^* 
*ioapi.h:181:5:* *error: *unknown type name ‘*open_file_func*’ 
*    ^* 
*ioapi.h:182:5:* *error: *unknown type name ‘*tell_file_func*’ 
*    ^* 
*ioapi.h:183:5:* *error: *unknown type name ‘*seek_file_func*’ 
*    ^* 
*ioapi.h:194:21:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                    ^* 
*ioapi.h:195:22:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                     ^* 
*ioapi.h:196:23:* *error: *expected ‘*=*’, ‘*,*’, ‘*;*’, ‘*asm*’ or ‘*__attribute__*’ before 
‘*OF*’ 
*                      ^* 
*ioapi.c:* In function ‘*call_zopen64*’: 
*ioapi.c:33:46:* *warning: *comparison between pointer and integer 
*                                             ^* 
*ioapi.c:34:17:* *error: *invalid type argument of unary ‘***’ (have ‘*int*’) 
*                ^* 
*ioapi.c:37:17:* *error: *invalid type argument of unary ‘***’ (have ‘*int*’) 
*                ^* 
*ioapi.c:* In function ‘*call_zseek64*’: 
*ioapi.c:43:46:* *warning: *comparison between pointer and integer 
*                                             ^* 
*ioapi.c:44:17:* *error: *invalid type argument of unary ‘***’ (have ‘*int*’) 
*                ^* 
*ioapi.c:51:21:* *error: *invalid type argument of unary ‘***’ (have ‘*int*’) 
*                    ^* 
*ioapi.c:* In function ‘*call_ztell64*’: 
*ioapi.c:57:46:* *warning: *comparison between pointer and integer 
*                                             ^*

**Comment by petricf** [comment] 2017-08-10 15:17
Missed attachment - renamed to build.txt
[build.txt](https://github.com/jmcnamara/libxlsxwriter/files/1215398/build.txt)

**Comment by jmcnamara** [comment] 2017-08-10 16:41
What is the output of the following on your system:

```
git clone https://github.com/jmcnamara/libxlsxwriter.git
cd libxlsxwriter
make V=1

```

P.S. Could you post the output via the GitHub website (rather than email) and place it between verbatim commands ``` (3 backticks at the start and end).

**Comment by petricf** [comment] 2017-08-10 23:29
Find attached the screen output (test.txt)

System was configured for german output, so i prefixed the LANG variable.

Am Donnerstag 10 August 2017, 09:41:49 schrieb John McNamara:
> What is the output of the following on your system:
> 
> ```
> git clone https://github.com/jmcnamara/libxlsxwriter.git
> cd libxlsxwriter
> make V=1
> 
> ```
> 
> P.S. Could you post the output via the GitHub website (rather than email)
> and place it between verbatim commands ``` (3 backticks at the start and
> end).


petric@main ~/test $ LANG=en_US.UTF-8 git clone https://github.com/jmcnamara/libxlsxwriter.git
Cloning into 'libxlsxwriter'...
remote: Counting objects: 7625, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 7625 (delta 9), reused 21 (delta 7), pack-reused 7591
Receiving objects: 100% (7625/7625), 13.75 MiB | 5.02 MiB/s, done.
Resolving deltas: 100% (5635/5635), done.
petric@main ~/test $ cd libxlsxwriter
petric@main ~/test/libxlsxwriter $ LANG=en_US.UTF-8 make V=1
make -C third_party/minizip
make[1]: Entering directory '/home/petric/test/libxlsxwriter/third_party/minizip'
cc         -c -O3 -DNOCRYPT -DNOUNCRYPT ioapi.c
In file included from ioapi.c:29:0:
ioapi.h:135:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char* filename, int mode));
                                                   ^
ioapi.h:136:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef uLong    (ZCALLBACK *read_file_func)      OF((voidpf opaque, voidpf stream, void* buf, uLong size));
                                                   ^
ioapi.h:137:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef uLong    (ZCALLBACK *write_file_func)     OF((voidpf opaque, voidpf stream, const void* buf, uLong size));
                                                   ^
ioapi.h:138:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef int      (ZCALLBACK *close_file_func)     OF((voidpf opaque, voidpf stream));
                                                   ^
ioapi.h:139:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef int      (ZCALLBACK *testerror_file_func) OF((voidpf opaque, voidpf stream));
                                                   ^
ioapi.h:141:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef long     (ZCALLBACK *tell_file_func)      OF((voidpf opaque, voidpf stream));
                                                   ^
ioapi.h:142:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef long     (ZCALLBACK *seek_file_func)      OF((voidpf opaque, voidpf stream, uLong offset, int origin));
                                                   ^
ioapi.h:148:5: error: unknown type name ‘open_file_func’
     open_file_func      zopen_file;
     ^
ioapi.h:149:5: error: unknown type name ‘read_file_func’
     read_file_func      zread_file;
     ^
ioapi.h:150:5: error: unknown type name ‘write_file_func’
     write_file_func     zwrite_file;
     ^
ioapi.h:151:5: error: unknown type name ‘tell_file_func’
     tell_file_func      ztell_file;
     ^
ioapi.h:152:5: error: unknown type name ‘seek_file_func’
     seek_file_func      zseek_file;
     ^
ioapi.h:153:5: error: unknown type name ‘close_file_func’
     close_file_func     zclose_file;
     ^
ioapi.h:154:5: error: unknown type name ‘testerror_file_func’
     testerror_file_func zerror_file;
     ^
ioapi.h:158:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef ZPOS64_T (ZCALLBACK *tell64_file_func)    OF((voidpf opaque, voidpf stream));
                                                   ^
ioapi.h:159:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef long     (ZCALLBACK *seek64_file_func)    OF((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin));
                                                   ^
ioapi.h:160:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef voidpf   (ZCALLBACK *open64_file_func)    OF((voidpf opaque, const void* filename, int mode));
                                                   ^
ioapi.h:164:5: error: unknown type name ‘open64_file_func’
     open64_file_func    zopen64_file;
     ^
ioapi.h:165:5: error: unknown type name ‘read_file_func’
     read_file_func      zread_file;
     ^
ioapi.h:166:5: error: unknown type name ‘write_file_func’
     write_file_func     zwrite_file;
     ^
ioapi.h:167:5: error: unknown type name ‘tell64_file_func’
     tell64_file_func    ztell64_file;
     ^
ioapi.h:168:5: error: unknown type name ‘seek64_file_func’
     seek64_file_func    zseek64_file;
     ^
ioapi.h:169:5: error: unknown type name ‘close_file_func’
     close_file_func     zclose_file;
     ^
ioapi.h:170:5: error: unknown type name ‘testerror_file_func’
     testerror_file_func zerror_file;
     ^
ioapi.h:174:28: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 void fill_fopen64_filefunc OF((zlib_filefunc64_def* pzlib_filefunc_def));
                            ^
ioapi.h:175:26: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 void fill_fopen_filefunc OF((zlib_filefunc_def* pzlib_filefunc_def));
                          ^
ioapi.h:181:5: error: unknown type name ‘open_file_func’
     open_file_func      zopen32_file;
     ^
ioapi.h:182:5: error: unknown type name ‘tell_file_func’
     tell_file_func      ztell32_file;
     ^
ioapi.h:183:5: error: unknown type name ‘seek_file_func’
     seek_file_func      zseek32_file;
     ^
ioapi.h:194:21: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 voidpf call_zopen64 OF((const zlib_filefunc64_32_def* pfilefunc,const void*filename,int mode));
                     ^
ioapi.h:195:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 long    call_zseek64 OF((const zlib_filefunc64_32_def* pfilefunc,voidpf filestream, ZPOS64_T offset, int origin));
                      ^
ioapi.h:196:23: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 ZPOS64_T call_ztell64 OF((const zlib_filefunc64_32_def* pfilefunc,voidpf filestream));
                       ^
ioapi.c: In function ‘call_zopen64’:
ioapi.c:33:46: warning: comparison between pointer and integer
     if (pfilefunc->zfile_func64.zopen64_file != NULL)
                                              ^
ioapi.c:34:17: error: invalid type argument of unary ‘*’ (have ‘int’)
         return (*(pfilefunc->zfile_func64.zopen64_file)) (pfilefunc->zfile_func64.opaque,filename,mode);
                 ^
ioapi.c:37:17: error: invalid type argument of unary ‘*’ (have ‘int’)
         return (*(pfilefunc->zopen32_file))(pfilefunc->zfile_func64.opaque,(const char*)filename,mode);
                 ^
ioapi.c: In function ‘call_zseek64’:
ioapi.c:43:46: warning: comparison between pointer and integer
     if (pfilefunc->zfile_func64.zseek64_file != NULL)
                                              ^
ioapi.c:44:17: error: invalid type argument of unary ‘*’ (have ‘int’)
         return (*(pfilefunc->zfile_func64.zseek64_file)) (pfilefunc->zfile_func64.opaque,filestream,offset,origin);
                 ^
ioapi.c:51:21: error: invalid type argument of unary ‘*’ (have ‘int’)
             return (*(pfilefunc->zseek32_file))(pfilefunc->zfile_func64.opaque,filestream,offsetTruncated,origin);
                     ^
ioapi.c: In function ‘call_ztell64’:
ioapi.c:57:46: warning: comparison between pointer and integer
     if (pfilefunc->zfile_func64.zseek64_file != NULL)
                                              ^
ioapi.c:58:17: error: invalid type argument of unary ‘*’ (have ‘int’)
         return (*(pfilefunc->zfile_func64.ztell64_file)) (pfilefunc->zfile_func64.opaque,filestream);
                 ^
ioapi.c:61:29: error: invalid type argument of unary ‘*’ (have ‘int’)
         uLong tell_uLong = (*(pfilefunc->ztell32_file))(pfilefunc->zfile_func64.opaque,filestream);
                             ^
ioapi.c: In function ‘fill_zlib_filefunc64_32_def_from_filefunc32’:
ioapi.c:71:48: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     p_filefunc64_32->zfile_func64.zopen64_file = NULL;
                                                ^
ioapi.c:76:48: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     p_filefunc64_32->zfile_func64.ztell64_file = NULL;
                                                ^
ioapi.c:77:48: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     p_filefunc64_32->zfile_func64.zseek64_file = NULL;
                                                ^
ioapi.c: At top level:
ioapi.c:87:42: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static voidpf  ZCALLBACK fopen_file_func OF((voidpf opaque, const char* filename, int mode));
                                          ^
ioapi.c:88:42: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static uLong   ZCALLBACK fread_file_func OF((voidpf opaque, voidpf stream, void* buf, uLong size));
                                          ^
ioapi.c:89:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static uLong   ZCALLBACK fwrite_file_func OF((voidpf opaque, voidpf stream, const void* buf,uLong size));
                                           ^
ioapi.c:90:45: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static ZPOS64_T ZCALLBACK ftell64_file_func OF((voidpf opaque, voidpf stream));
                                             ^
ioapi.c:91:44: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static long    ZCALLBACK fseek64_file_func OF((voidpf opaque, voidpf stream, ZPOS64_T offset, int origin));
                                            ^
ioapi.c:92:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static int     ZCALLBACK fclose_file_func OF((voidpf opaque, voidpf stream));
                                           ^
ioapi.c:93:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 static int     ZCALLBACK ferror_file_func OF((voidpf opaque, voidpf stream));
                                           ^
ioapi.c: In function ‘fill_fopen_filefunc’:
ioapi.c:227:36: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zopen_file = fopen_file_func;
                                    ^
ioapi.c:228:36: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zread_file = fread_file_func;
                                    ^
ioapi.c:229:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zwrite_file = fwrite_file_func;
                                     ^
ioapi.c:230:36: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->ztell_file = ftell_file_func;
                                    ^
ioapi.c:231:36: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zseek_file = fseek_file_func;
                                    ^
ioapi.c:232:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zclose_file = fclose_file_func;
                                     ^
ioapi.c:233:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zerror_file = ferror_file_func;
                                     ^
ioapi.c: In function ‘fill_fopen64_filefunc’:
ioapi.c:239:38: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zopen64_file = fopen64_file_func;
                                      ^
ioapi.c:240:36: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zread_file = fread_file_func;
                                    ^
ioapi.c:241:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zwrite_file = fwrite_file_func;
                                     ^
ioapi.c:242:38: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->ztell64_file = ftell64_file_func;
                                      ^
ioapi.c:243:38: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zseek64_file = fseek64_file_func;
                                      ^
ioapi.c:244:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zclose_file = fclose_file_func;
                                     ^
ioapi.c:245:37: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     pzlib_filefunc_def->zerror_file = ferror_file_func;
                                     ^
make[1]: *** [Makefile:38: ioapi.o] Error 1
make[1]: Leaving directory '/home/petric/test/libxlsxwriter/third_party/minizip'
make: *** [Makefile:20: all] Error 2

**Comment by petricf** [comment] 2017-08-10 23:32
Find attached the screen output (test.txt) as requested.

[test.txt](https://github.com/jmcnamara/libxlsxwriter/files/1216615/test.txt)

**Comment by petricf** [comment] 2017-08-11 00:04
Compiler info:
```
petric@main ~/test/libxlsxwriter $ LANG=en_US.UTF-8 gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-5.4.0-r3/work/gcc-5.4.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/5.4.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 5.4.0-r3 p1.3, pie-0.6.5' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --disable-libmpx --enable-vtable-verify --enable-libvtv --enable-lto --without-isl --enable-libsanitizer
Thread model: posix
gcc version 5.4.0 (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 
```

Default include search paths are:
```
petric@main ~/test/libxlsxwriter $ echo | LANG=en_US.UTF-8 gcc -Wp,-v -x c - -fsyntax-only
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed
 /usr/include
End of search list.
```

**Comment by jmcnamara** [comment] 2017-08-11 12:20
I'm finding it very hard to reproduce this on other Linux systems even after installing minizip into the system. From a bit of googling it looks like it only occurs on Gentoo.

A couple of questions:

1. Is zconf.h installed on your system and if so where? For me it is in `/usr/local/include/zconf.h`.
2. What version of Gentoo are you using?
3. If I wanted to replicate a system to reproduce this in a VM what version of Gentoo would I have to install?

John

**Comment by petricf** [comment] 2017-08-11 13:02
1. zconf.h is in /usr/include 
2. amd64 13.0 (base) + kde plasma desktop
3. Usually follow https://gentoo.org/get-started/
   This will get you to a non-gui installation. The latest stable version should be ok.

Gentoo is a distribution where you compile (nearly) everything from source. It uses a ports like system (inspired from BSD ?) to manage the installed packages.

Which VM system you intend to use (VMware, Proxmox (linux kvm), VirtualBox, ...) ?

**Comment by jmcnamara** [comment] 2017-08-11 13:19
> Which VM system you intend to use (VMware, Proxmox (linux kvm), VirtualBox, ...) ?

Virtualbox

**Comment by petricf** [comment] 2017-08-11 13:43
Should be installable w/o a problem. I use proxmox (http://pve.proxmox.com) for my test installations - so i can't provide a VM directly.
But this may help: http://www.osboxes.org/gentoo/

**Comment by jmcnamara** [comment] 2017-08-12 01:36
Hi,

I got a Gentoo VM built and I was able to replicate the issue. It is in the category best described as "interesting".

It turns out that it is caused by Gentoo redefining a macro in  libs zconf. Because why not fix a "[bad](https://bugs.gentoo.org/show_bug.cgi?id=383179)" macro name and let some poor schmucks downstream tear their hair out for a day or two.

Anyway, I've pushed a fix to master and tested it on Gentoo with the standard (non cmake) make system.

Let me know if you have any issues and if you want it packaged into a release.

The cmake solution will have to be patched separately and probably not in the short term.

John

**Comment by petricf** [comment] 2017-08-12 07:08
Thanks for your efforts.

I can confirm that your fix works for the Makefile based build.

The patches i posted on top of this issue also works for me. I can live with that.
You do not have to make a release only driven by the change above.

Could you consider adding a cmake option to use a system wide installed minizip instead of the packaged one ?

**Comment by jmcnamara** [comment] 2017-08-12 13:30
> You do not have to make a release only driven by the change above.

Ok. I thought that maybe your were going to submit a port/ebuild for libxlsxwriter to Gentoo. If not I'll just let the change trickle into the next release.



> Could you consider adding a cmake option to use a system wide installed minizip instead of the packaged one

To be clear: the issues isn't that there is a system wide minizip since that isn't an issue on Ubuntu, Fedora or other systems. The issue is that the Gentoo maintainers patch the standard zlib/zconf headers to redefine a macro name that they don't like. This causes programs that use those macros to not compile.

I'll look into a fix in the CMake files. In the meantime you can build with CMake as follows:

```
cd libxlsxwriter
cd cmake # or wherever
cmake -D CMAKE_C_FLAGS='-DOF=_Z_OF' ..
make 
```

**Comment by jmcnamara** [comment] 2017-08-12 13:56
> Could you consider adding a cmake option to use a system wide installed minizip instead of the packaged one ?

This issue is now fixed on master for cmake and make.

@Alexhuszagh Can you have a quick look at CMake fix: f256dc2ae9b3890d0df7ae92f234a7f7db5039f7 to see if everything looks okay. No rush.

**Closed by jmcnamara** 2017-08-12 13:56 UTC
Labels: bug, cmake, short term

**Comment by petricf** [comment] 2017-08-12 17:28
I've added the ebuild for 0.7.2 to gentoo bugtracker: https://bugs.gentoo.org/show_bug.cgi?id=627452

This ebuild-version includes the two patches i created for using the system minizip. They will be applied during the build process.

As soon as 0.7.3 (or whatever version the fixed release gets) is out (and i get knowledge of it) i will update the ebuild for gentoo and remove the patches.

**Comment by jmcnamara** [comment] 2017-08-12 20:30
Version 0.7.3 is available now. Thanks for submitting the ebuild file.

**Comment by petricf** [comment] 2017-08-13 14:53
Confirmed - patches are no more required for Gentoo.

I've posted an updated ebuild to https://bugs.gentoo.org/show_bug.cgi?id=627452.

**Comment by jmcnamara** [comment] 2017-08-14 10:22
Thanks for that. Let me know if it gets added.

P.S. There is a feature request to use system minizip when possible, that you might be interested in. See: #119.
