### ISSUE TITLE
Corrupted Excel files after inserting image with filename containing non-latin characters

### ISSUE THREAD

**Issue by RaFaeL-NN** [jmcnamara/libxlsxwriter#238] opened 2019-07-19 10:30 UTC
If I have an image with non-latin (russian) filename ("лого.png"), I'm using worksheet_insert_image(worksheet, 10, 15, "лого.png"). The library is using under Windows. I have to send a filename without UTF encoding, otherwise I got an error 9. I get "no error" with creation the xlsx file without encoding image filename, but the file is corrupted on opening in Excel (drawing1.xml). I think, it is because of copying original filename to tag "descr" without encoding to UTF-8 (may be there is an another problem, really I don't know). Corrupted file attached
[Report.xlsx](https://github.com/jmcnamara/libxlsxwriter/files/3410683/Report.xlsx).

**Comment by jmcnamara** [comment] 2019-07-19 10:47
Can you add a small working example that demonstrates the issue with the sample image.

**Comment by RaFaeL-NN** [comment] 2019-07-19 13:30
OK
[test.zip](https://github.com/jmcnamara/libxlsxwriter/files/3411251/test.zip)

**Comment by jmcnamara** [comment] 2019-07-19 19:26
Seems to be a Windows only issue. It works fine on Linux/Mac OS.

I'll look into a fix.

**Comment by m00k12** [comment] 2019-08-09 11:27
I'm seeing something very similar, writing from Linux.

Passing <code>worksheet_write_string()</code> a string that contains an invalid ASCII character causes Excel to fail to load the entire worksheet (LibreOffice dropped just the affected column of the worksheet).  The example of this was a string containing a byte 0xf6, commonly interpreted as 'o diaeresis' or an 'o' with an umlaut where I am.

The fix may be to check that the passed string is valid UTF-8 or pure ASCII and return an  <code>lxw_error</code> code and omit the cell so we get a chance of an error at generation time, rather than when loading into Excel.

For reference Excel did produce a warning pointing to the invalid character in the input file, it was at column 549511 of a line over a million chars long and took a hex editor to find!

>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
>Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Illegal xml character. Line 2, column 549511.

Great work though!

**Comment by jmcnamara** [comment] 2019-08-09 12:19
> I'm seeing something very similar, writing from Linux.

Technically it isn't quite the same on Linux.

In general the filename and any strings the you use in libxlsxwriter (or Excel) must be UTF-8.

The issue reported, as far as I can see, relates to reading a Unicode .png file with the zlib interfaces on Windows. I still haven't had a chance to validate it in MSVC but I tried it on Linux and it works as expected.

> The fix may be to check that the passed string is valid UTF-8 or pure ASCII and return an `lxw_error` code and omit the cell so we get a chance of an error at generation time, rather than when loading into Excel.

I think, for now, the user will just have to ensure that they are passing valid UTF-8 strings to the library.

**Comment by Alexhuszagh** [comment] 2019-09-16 16:12
@jmcnamara, @m00k12 It would be fairly easy to provide a check that a C-string is valid UTF-8.

A comprehensive implementation would be (this should work in C89 as long as `stdint.h` has `uint8_t` and `uintptr_t`, both of which should be likely conditions. It should work in C99 or later always.

```c
#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/**
 * Magic number to determine the number of continuation bytes required.
 *  A UTF-8 code point is either valid ASCII (highest bit is 0),
 *  or it comprises a start + continuation bytes.
 */
static const uint8_t UTF8_BYTES[256] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,5,5,5,5};

/* Get the distance between two pointers. */
__inline size_t distance(uint8_t const* first, uint8_t const* last)
{
    uintptr_t dist = (uintptr_t)last - (uintptr_t) first;
    return (size_t)dist;
}

/* Determine if byte is a valid continuation byte. */
__inline bool is_continuation_byte(uint8_t c)
{
    return c >= 0x80 && c<= 0xbf;
}

/* Determine if byte is a valid start byte. */
__inline bool is_start_byte(uint8_t c)
{
    return c > 0xbf;
}

/* Determine if the byte is valid. */
__inline bool is_valid_byte(uint8_t byte, bool is_continuation)
{
    if (is_continuation) {
        return is_continuation_byte(byte);
    }
    return byte < 0x80 || is_start_byte(byte);
}

/**
 * Decode an entire codepoint and increment first.
 *  :param first: Pointer to a pointer the first character in the sequence.
 *  :param last: Pointer to 1-past last character. Normally the null terminator.
 */
bool is_valid_codepoint(uint8_t const* * first, uint8_t const* last)
{
    assert(first != NULL);
    assert(last != NULL);

    uint8_t const* ptr = *first;
    assert(ptr != NULL);

    /* Get the expected number of UTF-8 continuation bytes in the code point. */
    uint8_t byte_count = UTF8_BYTES[*ptr];

    /**
     * If the required number of bytes would overrun our buffer,
     * exit early. We need to calculate the distance between our ptr
     * and last, and see if the byte_count >= that distance, since
     * incrementing ptr may go outside of the array, and could therefore
     * be optimized out.
     */
    size_t dist = distance(ptr, last);
    if (byte_count >= dist) {
        return false;
    }

    /**
     * This may seem to skip a check, since this loop doesn't care if the
     * first byte is a start or ascii byte. However, this is already
     * checked by the `UTF8_BYTES[*ptr]`, so the initial check is redundant
     * either way.
     *
     * NOTE: Fallthrough is **intentional**.
     */
    bool is_continuation = false;
    switch (byte_count) {
        case 5:
            /**
             * The original UTF-8 specification allowed for 6-byte code points.
             * The maximum now is 4.
             */
            return false;
        case 4:
            /**
             * The original UTF-8 specification allowed for 6-byte code points.
             * The maximum now is 4.
             */
            return false;
        case 3:
            if (!is_valid_byte(*ptr++, is_continuation))
                return false;
            is_continuation = true;
        case 2:
            if (!is_valid_byte(*ptr++, is_continuation))
                return false;
            is_continuation = true;
        case 1:
            if (!is_valid_byte(*ptr++, is_continuation))
                return false;
            is_continuation = true;
        case 0:
            if (!is_valid_byte(*ptr++, is_continuation))
                return false;
    }

    /* Increment our in-out variable. */
    *first = ptr;

    return true;
}

/**
 * Check if a UTF-8 sequence is valid.
 *  :param first: Pointer to the first character in the sequence.
 *  :param last: Pointer to 1-past last character. Normally the null terminator.
 */
bool is_valid_utf8(uint8_t const* first, uint8_t const* last)
{
    assert(first != NULL);
    assert(last != NULL);

    while (first != last) {
        if (!is_valid_codepoint(&first, last)) {
            return false;
        }
    }
    return true;
}

/**
 * Check if a UTF-8 C-string is valid.
 */
bool is_valid_utf8_cstring(char const* cstring)
{
    uint8_t const* first = (uint8_t const*) cstring;
    size_t length = strlen(cstring);
    uint8_t const* last = first + length;
    return is_valid_utf8(first, last);
}

/* REMOVE AFTER HERE */
/* --------------------------------- */
/**
 * Various tests to ensure the UTF-8 validator works.
 */

#include <stdio.h>

int main()
{
    /* Valid ASCII */
    const char data1[] = {72, 97, 110, 103, 117, 108, 0};
    printf("ASCII is valid: %d\n", is_valid_utf8_cstring(data1));

    /* Valid UTF-8 (Hangul) */
    const char data2[] = {-19, -107, -100, -22, -75, -83, -20, -106, -76, 0};
    printf("UTF-8 is valid: %d\n", is_valid_utf8_cstring(data2));

    /* Invalid Code Point */
    /* -19 (237 as uint8_t) should be followed by 2 continuation bytes. */
    /* Here, we only have 1 continuation byte. */
    const char data3[] = {-19, -107, 72, -19, -107, -100, -22, -75, -83, -20, -106, -76, 0};
    printf("Invalid code point is valid: %d\n", is_valid_utf8_cstring(data3));

    /* Invalid Continuation Byte */
    /* -107 (149 as uint8_t) is a continuation bytes without any start byte. */
    const char data4[] = {-107, 72, -19, -107, -100, -22, -75, -83, -20, -106, -76, 0};
    printf("Invalid continuation byte is valid: %d\n", is_valid_utf8_cstring(data4));

    return 0;
}
```

**Comment by Alexhuszagh** [comment] 2019-09-16 16:26
If the UTF-8 validator has any interest, I'd gladly submit a PR with it included. However, I believe this only addresses the second issue raised, and not the original bug on MSVC (which I will look into later).

**Comment by jmcnamara** [comment] 2019-09-16 16:34
> If the UTF-8 validator has any interest, I'd gladly submit a PR with it included.

@Alexhuszagh Thanks for the input, but I don't think that is a feature that I want to add/maintain.

**Comment by Alexhuszagh** [comment] 2019-09-16 16:44
@jmcnamara No worries, just figured I'd make the suggestion since I've previously implemented this code.

**Comment by m00k12** [comment] 2019-09-16 17:39
I used libiconv to clean all strings before output.

**Comment by jmcnamara** [comment] 2019-10-06 11:44
I don't work on Windows very often so I keep failing to get to this to debug it. Maybe someone else on the thread can have a look.

A test program would look like this:

```C
#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = workbook_new("test.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    worksheet_insert_image(worksheet, 0, 0, "лого.png");

    workbook_close(workbook);

    return 0;
}
```

You can use any png image. The source file should be UTF-8 encoded.

There are two potential issue.


The first is that libxlsxwriter needs to open and parse the image added with `worksheet_insert_image()` to read the image metadata such as height, width and DPI.  The 'fopen()' on the filename to read the image metadata probably won't work for a file with an non-ASCII name:

https://github.com/jmcnamara/libxlsxwriter/blob/master/src/worksheet.c#L5546

```C

    /* Check that the image file exists and can be opened. */
    image_stream = fopen(filename, "rb");
    if (!image_stream) {
        LXW_WARN_FORMAT1("worksheet_insert_image()/_opt(): "
                         "file doesn't exist or can't be opened: %s.",
                         filename);
        return LXW_ERROR_PARAMETER_VALIDATION;
    }
```

The second, potential issue, is when the file is added to the zip file:

https://github.com/jmcnamara/libxlsxwriter/blob/master/src/packager.c#L245

If someone who works on Windows more regularly, and knows how these types of filename handling works, can take a look that would be great.

+ @utelle

**Comment by RaFaeL-NN** [comment] 2019-10-06 12:48
https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2017

fopen supports Unicode file streams. To open a Unicode file, pass a ccs flag that specifies the desired encoding to fopen, as follows.

FILE *fp = fopen("newfile.txt", "rt+, ccs=encoding");

Allowed values of encoding are UNICODE, UTF-8, and UTF-16LE.

**Comment by RaFaeL-NN** [comment] 2019-10-06 13:03
fopen() in Windows works only with ANSI filenames. Another solution is in converting ANSI filename with MultiByteToWideChar(0,... and WideCharToMultiByte(650001,... before putting it in XML, not before fopen()

**Comment by jmcnamara** [comment] 2019-10-06 20:25
I've pushed a fix to the `win_fopen` branch that uses `_wfopen()` on Windows.

I build that branch into a library and compile the above code against it. It worked as expected with a sample лого.png image file:

![aa_image](https://user-images.githubusercontent.com/94267/66275367-cd0a3680-e87f-11e9-9a24-21894069ccdc.png)



Note, the source file must be UTF-8 encoded.

**Comment by RaFaeL-NN** [comment] 2019-10-06 21:42
No difference. I am using MinGW, not MSVC. Is a patch applicable for it?

**Comment by RaFaeL-NN** [comment] 2019-10-06 22:09
P.S. It works with comments #ifdef _MSC_VER line and some lines at bottom, and replacing _MAX_PATH with 260

**Comment by jmcnamara** [comment] 2019-10-06 22:13
Ok. Good.

Can you try replace _MSC_VER like this, and test it:

```diff
diff --git a/src/utility.c b/src/utility.c
index 4a63745..661ea16 100644
--- a/src/utility.c
+++ b/src/utility.c
@@ -602,7 +602,11 @@ lxw_hash_password(const char *password)
 }

 /* Make a simple portable version of fopen() for Windows. */
-#ifdef _MSC_VER
+#ifdef __MINGW32__
+#undef _WIN32
+#endif
+
+#ifdef _WIN32

 #include <windows.h>
```

**Comment by RaFaeL-NN** [comment] 2019-10-06 22:24
Don't work. If I undef _WIN32, how can it works?

**Comment by jmcnamara** [comment] 2019-10-06 22:35
What version of MinGW are you using? 32 or 64bit and can you send a link to the one you download/use?

**Comment by RaFaeL-NN** [comment] 2019-10-06 22:51
32bit. Really I don't know version, because I am using it just for making dll of libxlsxwriter and never updating it for years after installing ~3 years ago. You can try the latest one from mingw.org

**Comment by jmcnamara** [comment] 2019-10-07 09:31
I understand that this fix works in your case but I'm not convinced that it is a general issue (outside of MSVC).

The `fopen()` function should work without modification in MinGW32 without modification. Here is an example:

```bash

$ uname -a
MINGW32_NT-10.0-WOW john 2.6.0(0.304/5/3) 2016-09-07 21:23 i686 Msys

$ cd ~/libxlsxwriter

$ git checkout master

$ git pull origin
...

$ make examples V=1
make -C examples
...

# Add the worksheet_insert_image() line to an existing utf8 example.
$ vim examples/utf8.c

# Here is the resultant file:
$ cat examples/utf8.c
/*
 * A simple Unicode UTF-8 example using libxlsxwriter.
 *
 * Note: The source file must be UTF-8 encoded.
 *
 * Copyright 2014-2018, John McNamara, jmcnamara@cpan.org
 *
 */

#include "xlsxwriter.h"

int main() {

    lxw_workbook  *workbook  = workbook_new("utf8.xlsx");
    lxw_worksheet *worksheet = workbook_add_worksheet(workbook, NULL);

    worksheet_write_string(worksheet, 2, 1, "Это фраза на русском!", NULL);
    worksheet_insert_image(worksheet, 0, 0, "лого.png");


    return workbook_close(workbook);
}

# Copy a suitable image.
$ cp test/functional/src/images/red.png лого.png

# Re-make the examples.
$ make examples V=1
make -C examples
make[1]: Entering directory '/home/jmcnam2/libxlsxwriter/examples'
cc -I../include -g -Wall -Wextra utf8.c -o utf8 ../src/libxlsxwriter.a -lz
make[1]: Leaving directory '/home/jmcnam2/libxlsxwriter/examples'

# Run the example. Note, there are no errors/warnings.
$ ./examples/utf8.exe

# Note the output file.
$ ls -ltr
total 137
drwxr-xr-x 1 jmcnam2 Domain Users     0 Oct 18  2017 dev
...
-rw-r--r-- 1 jmcnam2 Domain Users   200 Oct  7 09:28 лого.png
drwxr-xr-x 1 jmcnam2 Domain Users     0 Oct  7 09:28 examples
-rw-r--r-- 1 jmcnam2 Domain Users  6854 Oct  7 09:29 utf8.xlsx

```

Output:

![aa_image](https://user-images.githubusercontent.com/94267/66299698-f496e880-e8eb-11e9-8e31-60035ffe0020.png)

Can you try reproduce in a more recent version of MinGW using the example above and the more general libxlsxwriter MinGW instructions here: https://libxlsxwriter.github.io/getting_started.html#gsg_ming

**Comment by RaFaeL-NN** [comment] 2019-10-07 10:05
> The `fopen()` function should work in MinGW32 without modification.

No. A program, compiled in MinGW based on **msvcrt.dll from Windows**. fopen() in msvcrt.dll use ANSI only

**Comment by jmcnamara** [comment] 2019-10-07 10:54
> No. A program, compiled in MinGW depends on **msvcrt.dll from Windows**. fopen() in msvcrt.dll use ANSI only

I don't understand. Why does the MinGW example I show above work with fopen and a non-ansii filename?

**Comment by RaFaeL-NN** [comment] 2019-10-07 11:01
What version of Windows and what version of msvcrt.dll?

**Comment by jmcnamara** [comment] 2019-10-07 11:08
> What version of Windows and what version of msvcrt.dll? 

Windows 10 and msvcrt.dll ver 7.0.16299.

**Comment by RaFaeL-NN** [comment] 2019-10-07 11:14
Can you attach an archive with utf8.exe and лого.png?

**Comment by jmcnamara** [comment] 2019-10-07 12:11
I can't attach them but you can rebuild them by following my instructions above, I used [MSYS2](http://www.msys2.org/) and the following setup:

```bash
pacman -S git gcc make zlib-devel

# Clone and build libxlsxwriter.
git clone https://github.com/jmcnamara/libxlsxwriter.git
cd libxlsxwriter/
make
```

**Comment by RaFaeL-NN** [comment] 2019-10-07 12:12
I have to check what your filename is in ANSI on disk, not in UTF-8

**Comment by jmcnamara** [comment] 2019-10-08 10:50
> I have to check what your filename is in ANSI **on disk** (EB EE E3 EE 2E 70 6E 67), not in UTF-8 (D0 BB D0 BE D0 B3 D0 BE 2E 70 6E 67). How can you rename it to Win-1251 without russian locale?

It would be better if you built the environment with the instructions I gave above and tried it yourself.

Alternatively, you could give detailed step on how I can replicate your environment.

Anyway, the filename is UTF-8 encoded (it has to be to match the ut8.c example encoding):

```bash
$ ls -1 *.png | xxd
00000000: d0bb d0be d0b3 d0be 2e70 6e67 0a         .........png.
```

**Comment by RaFaeL-NN** [comment] 2019-10-08 14:32
> Anyway, the filename is UTF-8 encoded
Well. But the **original issue is with filename in ANSI** (EB EE E3 EE 2E 70 6E 67) (read first post). In Windows filenames are stored in ANSI, not in UTF-8. It filename is D0 BB D0 BE D0 B3 D0 BE 2E 70 6E 67 in NOT will be displaying at Windows Explorer (and all other programs) as "лого.png", but as "Р»РѕРіРѕ.png" (not readable).  If I have file "Р»РѕРіРѕ.png" (D0 BB D0 BE D0 B3 D0 BE 2E 70 6E 67) of course, I can insert it by lib. But I have not, and nobody have. So, I need a way to insert image with filename "лого.png" in ANSI (EB EE E3 EE 2E 70 6E 67) and to have a correct xlsx on output

**Comment by Alexhuszagh** [comment] 2019-10-08 14:48
> I used libiconv to clean all strings before output.

Iconv is great, the main issue is the licensing which is obviously not compatible here. Also, not worth a dependency, I'm guessing.

**Comment by Alexhuszagh** [comment] 2019-10-08 15:23
A simple conversion utility (and an example showing it works) is as follows:

```c
#include <windows.h>
#include <stdlib.h>


wchar_t* utf8_to_utf16(const char* string)
{
    // We need to call MultiByteToWideChar twice:
    //  Once to get the length of the output string, to avoid overflows.
    //  The second time to actually convert it.
    int count = MultiByteToWideChar(CP_UTF8, 0, string, -1, NULL, 0);
    if (count == 0) {
        // Did not succeed, return null pointer.
        return NULL;
    }
    wchar_t* wstr = malloc(sizeof(wchar_t) * count);
    if (MultiByteToWideChar(CP_UTF8, 0, string, -1, wstr, count) == 0) {
        // Did not succeed, free and return null pointer.
        free(wstr);
        return NULL;
    }
    return wstr;
}


int main()
{
    const char* narrow = "path/to/한글.xlsx";
    wchar_t* wide = utf8_to_utf16(narrow);

    // Print as a string.
    wprintf(L"Printing as a string: %ls\n", wide);

    // Print bytes, to confirm it's UTF-16.
    wprintf(L"Printing as an array: [");
    size_t length = wcslen(wide);
    for (size_t i = 0; i < length; i++) {
        char* item = (char*)&wide[i];
        wprintf(L"%d, %d, ", item[0], item[1]);
    }
    wprintf(L"]\n");
    free(wide);

    return 0;
}
```

This should be sufficient to fix the issue, along with any NULL-checks to ensure the path isn't NULL (which may happen due to invalid input, or memory errors) while writing to file.

**Comment by jmcnamara** [comment] 2019-10-09 09:47
@Alexhuszagh Thanks for that.

**Comment by jmcnamara** [comment] 2019-10-09 09:49
@RaFaeL-NN 
> So, I need a way to insert image with filename "лого.png" in ANSI

Ok. That should be possible to support. I'll add a workaround soon.

**Comment by RaFaeL-NN** [comment] 2019-10-30 12:33
Good. Can you move _description_ next to _y_scale_ in _lxw_image_options_? As you know, I can not use С headers and I have to create my own data structures before sending data to lib. Of course, I can insert dummy empty variables but I hope, you'll change 

`typedef struct lxw_image_options {

    /** Offset from the left of the cell in pixels. */
    int32_t x_offset;

    /** Offset from the top of the cell in pixels. */
    int32_t y_offset;

    /** X scale of the image as a decimal. */
    double x_scale;

    /** Y scale of the image as a decimal. */
    double y_scale;

    lxw_row_t row;
    lxw_col_t col;
    char *filename;
    char *description;`

to

`typedef struct lxw_image_options {

    /** Offset from the left of the cell in pixels. */
    int32_t x_offset;

    /** Offset from the top of the cell in pixels. */
    int32_t y_offset;

    /** X scale of the image as a decimal. */
    double x_scale;

    /** Y scale of the image as a decimal. */
    double y_scale;

    char *description;
    lxw_row_t row;
    lxw_col_t col;
    char *filename;
`

**Comment by jmcnamara** [comment] 2019-11-10 20:03
> Good. Can you move description next to y_scale in lxw_image_options? 

Yes, I will. In fact I'm going to refactor the structs used in APIs so that all public fields are documented and available and the structs will be different internally if they contain any additional metadata that isn't public. I'll start with `lxw_image_options` as a test.

Once the `description` field is available publicly you can set it to "" (blank string) and the description/filename won't be copied internally and won't corrupt the file if it isn't UTF8. That should allow you to specify any encoding you want for the program to read the image file.

**Comment by jmcnamara** [comment] 2019-11-17 19:38
I'm going to close this issue. I'd recommend setting the description fields of `lxw_image_options` to "" (blank string) to prevent any non-utf8 chars getting copied into the file and corrupting it.

**Closed by jmcnamara** 2019-11-17 19:38 UTC
Labels: awaiting user feedback

**Comment by RaFaeL-NN** [comment] 2019-11-17 19:40
I tested it (user 'description'  field) and it works good. So, for now and for me the solution of the original issue is of copying the UTF8-encoded filename to description if user omit 'description' field. I think a commit with lxw_fopen actually does not needed

**Comment by jmcnamara** [comment] 2019-11-20 10:58
> I think a commit with lxw_fopen actually does not needed

Yes. It wasn't needed for your case. It is still probably a worthwhile fix for people using MSVC though.
