### ISSUE TITLE
Resetting format

### ISSUE THREAD

**Issue by algaspar** [jmcnamara/libxlsxwriter#372] opened 2022-05-11 15:11 UTC
I had a situation where I wanted to add a second line to some descriptive cells.  I did a check as to whether the cell had the extra information, and if it did set the format to wrap.

I am alternating between a colored row and a row that is just formatted with a wrapping format called "title". The logic I have for the formatting looks like this:

```C
if (Desc.empty())

{

	worksheet_write_string(worksheet2, row, 1, tmpStr, justcolor);  //no wrap
	
}

else

{

	worksheet_write_string(worksheet2, row, 1, tmpStr, title);  // wrapped row 
	
}
```
This seems to work and the colored rows that aren't wrapped are fine.  

I have identical code where I am writing out rows with no color background.  I have tried setting the format to NULL there and to a "justplain" format that just sets the font to the default Colibri.  On these rows with no color, once one row is set to wrap all of the following rows without color wrap as well.  This means that even rows without the additional description stay wide.  

Do I need to make my "justplain" format set a color (white) rather than the font?  Is there a better way?  I titled this as "Resetting format" as I just wanted the format to revert to plain/unformatted when there wasn't an extra description; so I thought NULL would work...

Thanks--

Al

**Comment by jmcnamara** [comment] 2022-05-11 18:12
It is hard, just from that description, to see what the issue is. Could you add a small complete program that demonstrates the issue.

**Comment by algaspar** [comment] 2022-05-11 18:22
Well, I tried making my "justplain" format to be explicitly LXW_COLOR_WHITE, but it didn't help.  I'll write something up and post it to you.

Thanks!

**Comment by jmcnamara** [comment] 2022-06-04 15:23
You will need to submit a small, complete, compilable example that demonstrates the issue.

**Comment by jmcnamara** [comment] 2022-06-20 23:21
Closing due to the lack of a reproducible example.

**Closed by jmcnamara** 2022-06-20 23:21 UTC
Labels: awaiting user feedback

**Comment by algaspar** [comment] 2022-06-21 11:39
Thank you.  I will submit this again, if I have a reproducible example.  My
apologies for not closing it earlier.

--Al
